### ISSUE TITLE
lending: add non-backed loans

### ISSUE THREAD

**Issue by marbar3778** [marbar3778/Entropy#3]
## Summary

Enable non-backed loans for margin accounts. 

This will be an extension of the token lending contract. 

To know which accounts are allowed to take these loans a whitelist or unique identifier is needed.

**Comment by marbar3778** [comment]
on creation of the margin account, the contract needs to add a new entry to the whitelist on the lending contract

**Comment by marbar3778** [comment]
Should we pay the interest rate on the opening of the loan or the closing? 

The opening simplifies something's, but after is still possible. This may affect liquidation price though.

**Comment by cmwaters** [comment]
I thought it would be easier to calculate on closing because we don't know what the duration of the loan is

**Comment by marbar3778** [comment]
Changing it to after. But the rate is different then the normal one.

**Comment by marbar3778** [comment]
closing this based off discusison
