### ISSUE TITLE
margin account semantics

### ISSUE THREAD

**Issue by marbar3778** [marbar3778/Entropy#9]
This issue is meant to discuss margin account semantics.

Creation:
- on creation the margin account should enter its program_id or some identifier into a whitelist in the lending contract. 

Deposit:

Withdraw:
- When a margin account is emptied (total value goes to 0) we should mark the account for cleanup by removing the rent exemption deposit. 

Trade:

Liquidate:
- Anyone can call this function, but it will only execute if the account in question is actually ready to be liquidated.
- There is a liquidation function also on the lending contract. The liquidation of a trade would not execute the lending contract liquidation because there is no obligation to liquidate. Here, liquidation will merely call repay, this repay will be the normal function call till the lending contract is extended to support margin repays

Deleverage:
- At a certain point in the trades life it may hit a point where the borrowed money is getting to a point of higher risk. At this point a liquidation bot should submit a tx to do a partial close. We should set an upper limit to how much can be closed.

**Comment by cmwaters** [comment]
Deleverage could be combined with Liquidate where within the transaction, we just add a percentage of the trade that needs to be sold. 100% means complete liquidation

**Comment by austinabell** [comment]
> Deleverage could be combined with Liquidate where within the transaction, we just add a percentage of the trade that needs to be sold. 100% means complete liquidation

Why do we need there to be the functionality to liquidate part of the position? I don't think this is standard to allow, is it?

**Comment by marbar3778** [comment]
We can remove it. I was thinking the user may not want to close the entire position but instead reduce risk because they believe in the position.
